export const BALANCE = {
  arenaHalfSize: 170,
  enemyCount: 7,
  roundDuration: 180,
  scoreGoal: 10,
  deathLimit: 5,
  roundRestartDelay: 4.5,
  player: {
    accel: 78,
    maxSpeed: 54,
    boostSpeed: 96,
    boostDrain: 0.42,
    boostRecharge: 0.24,
  },
  enemy: {
    baseMaxSpeed: 35,
    evadeMaxSpeed: 48,
    accelScale: 0.46,
    baseFireCooldown: 0.9,
    minFireCooldown: 0.48,
    desiredRangeMin: 58,
    desiredRangeSpread: 38,
    respawnDelay: 3.8,
  },
  weapons: {
    laserSpeed: 150,
    laserDamage: 11,
    laserCooldown: 0.12,
    missileSpeed: 78,
    missileDamage: 38,
    missileCooldown: 1.45,
    missileLockTime: 0.65,
  },
} as const;
